### ISSUE TITLE
Moving debian/ to top level

### ISSUE THREAD

**Issue by lweberk** [SOCI/soci-pkg#6]
Hi,

anything speaking against it?. I would have the necessary merge request for you.

Blockers:
* Move LICENSE_1_0.txt from src/ to repository root. Otherwise I got the changes running without changing anything outside the debian/*.

Best regards,
~lweberk

**Comment by mloskot** [comment]
I'm not sure I understand exactly where do you want to move the debian folder.
Also, SOCI LICENSE_1_0.txt is in top-level of https://github.com/SOCI/soci repository.

**Comment by lweberk** [comment]
True for `master`, not so for `release/3.2`. Is there an explanation to how branching is handled in the project?

**Comment by lweberk** [comment]
Sorry, I'm realising my phrasing of the issue to have been poorly concieved. What was meant is that currently the debian/ folder of soci-pkg has to be checked out to soci/src in the upstream repository for it to successfully build.
With few changes this can be changed to debian/ being checked out into the top level dir of soci (which is more natural).

**Comment by mloskot** [comment]
If possible, we would like to keep the debian content, as well as other packaging system files, in soci-pkg repository. At least for now.

Other than that, there is no requirements how soci-pkg is structured.
So, feel free to do in soci-pkg whatever Debian recommends.

**Comment by mloskot** [comment]
@lweberk regarding your question about branches, I've updated the [Contributing](https://github.com/SOCI/soci/wiki/Contributing) wiki.

**Comment by lweberk** [comment]
Ok. No problem with that. It would obsolete #8 though, is that your intention? In my opinion it would greatly simplify distribution if debian/* is split off into a new repository (for example called soci-pkg-debian) and incorporated into soci (the source code repository) via submodule. This way you can interlock a specific branch and version in the former into a specific branch and version of the latter. No offsetting between upstream and packaging directives.

Great. Thanks.

**Comment by OniDaito** [comment]
Hello there! I've been seeing lots of emails on my day off so I thought I'd get back to it on my return. 
Previously, I actually included the debian folder anyway, with a stack of gitignore directives. It works but isn't neat. Symlinking works too I've found but again, not optimal.

Iweberk, are you referring to Git Submodules: http://git-scm.com/book/en/v2/Git-Tools-Submodules

I quite like this idea and I'm thinking about implementing it here, or at least, as a separate project. Could then do the same for rpm and arch?

**Comment by mloskot** [comment]
I don't mind if we create `soci-pkg-*` repositories.
I don't mind if we link them as submodules.

So, whoever is interested in maintaining the packages and in making his/her work easier, it's their call.

If no objections arrive from active developers @vadz, @pfedor and package maintainers @denisarnaud @juliantaylor, please, outline the steps you want me to run in the main `soci` repository and I'll do it.

**Comment by OniDaito** [comment]
More than happy to have a crack at this. I've been thinking about similar things for the packaging we are doing, and learning about proper submodules and tightening up the deb package we use would be a good use of my time.

**Comment by mloskot** [comment]
:+1:

**Comment by vadz** [comment]
I think the only important thing is that `debian` directory shouldn't be included in SOCI release tarballs as Debian people prefer to not have it there. Other than that I don't really have any opinions about this, although I do wonder if including the `soci` repository as a submodule into `soci-pkg-debian` might make more sense: after all, it's the packaging script that use SOCI to actually package it and not SOCI itself which uses them.

**Comment by mloskot** [comment]
@vadz The idea is to allow non-core SOCI developers to participate in packaging, hence separate `soci-pkg` repository. So, submodule sounds like a good solution. I agree it might make more sense to flip the direction as you suggested. :+1:

**Comment by lweberk** [comment]
It might sound weird coming from me since I advocated this in the first place, but I think its prone to a lot of troubles. Let me outline some points that make the whole submodule approach problematic:

1.- Submodules would only work properly if soci core would include debian/, fedora/ etc. into itself as a submodule. If you work in tight integration and make no distinction between your upstream version and downstream packaging (which we internally do to great success) this works geat. Unfortunatelly we have not only to consider a more heterogeneous reality; fedora, arch, and other distros which don't quite work the same way (I even ignored MS and Apple in the game), but also the fact that soci core should give limited attention to the packaging itself and keep the build environment as generic as possible, so distros can do their jobs with straight forward approaches for their own, without making life harder on other distros.

2.- Even if you proceed to add the submodule, and agree to maintain packaging this way, maintainers would require upstream commit access to keep the submodule references up to date. Core devs would probably not want to have to consider asking downstream every time they change something that *might, but just and only might* break some packaging submodule. Totally impracticable for them.

3.- Creating a clean repository dedicated for a specific distro's packaging and adding the sourcecode as submodule would add the benefit of being able to reference and interlock versions, but it would also be counterintuitive (at least fo the debian case), since debian/* goes top-level-embedded in the projects hierarchy. In short its a mess and would require a quite hacky packaging repository to comply with the distros way of packaging (at least for debian)

My two cents:
As anything touching core is probably a bad idea, and submoduling upstream into a packaging downstream kind of upside down, it would probably be more sensible to maintain a downstream full clone of the upstream soci core and maintain a debian/* structure inside, merging new upstream changes into this downstream. Unless you touch anything outside of debian/* or upstream decides to make a debian/* of their own, any merge would be a fast forward, porting debian/* with you into the the staging area of the next commit, which in turn would be a partular package version. This is the way debian does it with quite a few official packages, giving birth to a tool like git-buildpackage (dont particularly like it, but thats my own personal anti-auto-magical opinion). Made an example of this approach yesterday, just for testing purposes and to play around/get familliar with the approach at https://github.com/lweberk/test-soci-pkg . 

Please forgive the debian-centerdness, its just that I'm not familiar (at least not in depth) with packaging systems other than dpkg.

**Comment by OniDaito** [comment]
If I've understood correctly, I feel we are getting into a problem we don't need to solve, or rather, it's a problem developers solve as a matter of course.

What I mean is this. Lets make the debian, arch, fedora, whatever os packages as separate projects. The *developer* is responsible for including them as submodules, in their own local build systems if that's what *they* want. So long as we design the packaging projects in a way that allows easy includes, this will not be a headache for a dev; indeed, making something more elaborate might make things worse.

**Comment by lweberk** [comment]
@OniDaito Did you mean *developer* or *packager*?

**Comment by OniDaito** [comment]
I suppose in this instance I mean the packager, though I do both here. 
This approach should make it easy for both parties though I think.

**Comment by lweberk** [comment]
Concur on that.
