### ISSUE TITLE
Debian multiarch package schema support

### ISSUE THREAD

**Issue by lweberk** [SOCI/soci-pkg#7]
Hi,

anything speaking against this? would have a merge request for you if you want it.

It would:
* Make use of the non invasive `-DLIBDIR=/usr/lib/$(DEB_HOST_MULTIARCH)` approach depicted in #1 by @juliantaylor 

Best regards,
~lweberk

**Comment by mloskot** [comment]
@lweberk no objections, please submit pull request against current master.

You may also submit against [release/3.2](https://github.com/SOCI/soci/tree/release/3.2) branch, but there is no promise to release SOCI 3.2.4

**Comment by lweberk** [comment]
Wouldn't it be better against soci-pkg master for now? (at least until we have resolution on #8). Integration into upstream like discussed in #8, would automatically bring in changes pulled through here first.

**Comment by mloskot** [comment]
From my point, there is no need to target the `release/3.2`, which maintenance has low priority.
Due to limited resources, we try to focus on the `master` branch (SOCI 4.x), so it has high priority.

**Comment by lweberk** [comment]
Understandable, but think about further release/x.x branches. You might have an accompanying branch in packaging that supports packing release/3.2. Then things change im some way for a release/4.x, again you can maintain a separate branch in the packaging repo catering to packaging that particular version. Users of the library will always want to maintain a relation to a stable release, while master is to be considered the bleeding edge. 
Graphically:

soci:master <-- soci-pkg:master
soci:release/3.2 <-- soci-pkg:release/3.2
soci:release/4.x <-- soci-pkg:release/4.x

and so on. As you can see you can cater for as many branches as you want, without incurring the mess for patches having to be applied so compatibility of distribution can be preserved.

On top of that, it would be perfect if soci-pkg was a submodule on soci, this way the particular version of for ex. soci:release/(3.2 | 4.x) can reference a particular changeset hash in the analogous branch in soci-pkg. And you get unbroken buildability, regardless of the checkout of your choice in soci.

Sorry to drag this out, but I feel this could clear a lot of trouble for those distributing the code. We work with submodules internally and had good results in preventing version clashes. The parent repo just references the particular version of the submodule it needs to work properly, thus it becomes impossible for the submodule to break a particular version of it.

**Comment by OniDaito** [comment]
Have merged and am testing now. Cheers! :)

**Comment by lweberk** [comment]
Thx, let me know if it works for you.
